// File generated by FlutterFire CLI - manually recreated by Agent
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        // Not configured yet - ignoring to avoid runtime errors on iOS unless configured
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPNMJvz-8oqRFAnPHYCxriptz2VpIJ1YQ',
    appId: '1:302495854234:web:96af893495d3b058657923',
    messagingSenderId: '302495854234',
    projectId: 'rubaika-93c66',
    authDomain: 'rubaika-93c66.firebaseapp.com',
    storageBucket: 'rubaika-93c66.firebasestorage.app',
    measurementId: 'G-90PBE6GVC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrsR1i8XE6dlX3qelvaO6c_w7pYiD1g2E',
    appId: '1:302495854234:android:db79c32a119584a3657923',
    messagingSenderId: '302495854234',
    projectId: 'rubaika-93c66',
    storageBucket: 'rubaika-93c66.firebasestorage.app',
  );
}
